<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>WpfApp1</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data" />
  </ItemGroup>
</Project>
